name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  id-token: write # Ajouté pour l'authentification OIDC de Cosign

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COSIGN_EXPERIMENTAL: '1' # Nécessaire pour certaines fonctionnalités de Cosign
  # COSIGN_REPOSITORY: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} # Supprimé car il cause un problème avec cosign sign blob

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CSC_FOR_PULL_REQUEST: true # Ajouté pour forcer la signature sur les PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js application
        run: npm run build

      - name: Build and publish Windows
        run: npm run compose-publish

  build-macos:
    runs-on: macos-latest
    env:
      CSC_FOR_PULL_REQUEST: true # Ajouté pour forcer la signature sur les PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js application
        run: npm run build

      - name: Build and publish macOS
        run: npm run compose-publish

  build-linux:
    runs-on: ubuntu-latest
    env:
      CSC_FOR_PULL_REQUEST: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js application
        run: npm run build

      - name: Build and publish Linux
        run: npm run compose-publish
